version: "27.0.3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
        - mongodb_data:/data/db
  backend:
    build: ./backend
    environment:
      - GENERATE_SOURCEMAP=false
      - MONGO_URI=mongodb://mongodb:27017/todo_app
    ports:
      - "8001:8001"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    build: ./reactblog
    environment:
      - GENERATE_SOURCEMAP=false
    ports:
      - "3000:3000"
    volumes:
      - ./reactblog/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  mongodb_data:
  logs: